### ISSUE TITLE
Line 8 invalid syntax from my linux mint pc

### ISSUE THREAD

**Issue by jones263** [skickar/SpaceAPI#1]
tried to run the trackISS.py with the python command and got this error

 File "trackISS.py", line 8
    print(("Target acquired, tracking active: the location of the ISS is {}, {}.".format(lat,long))),print("Landmarks the station is visible from: ", g.country)
                                                                                                         ^
SyntaxError: invalid syntax

I'm new too linux and python. it might be me

I changed all "print" to "printf" and got error: 

Traceback (most recent call last):
  File "ytrackISS.py", line 1, in <module>
    from geopy.distance import geodesic
ImportError: No module named geopy.distance

**Comment by jones263** [comment]
changed all print to printf and got-

Traceback (most recent call last):
  File "ytrackISS.py", line 1, in <module>
    from geopy.distance import geodesic
ImportError: No module named geopy.distance

**Comment by Longicauda** [comment]
I am new to this as well but it appears to just be the print function location. I was able to move the second print function in line 8 down a line with an indent. On line 21 you have to add ; on the second print.

**Comment by despy49** [comment]
LOL) python does not need ';' at all. Works fine on kali 2019.2 with python3. Everything I had to do is pip3 install geopy geocoder
